### ISSUE TITLE
导航栏层级的bug

### ISSUE THREAD

**Issue by Ezgx** [zhaoo/hexo-theme-zhaoo#116]
导航栏的层级比标题低
```css
.navbar.transparent {
    z-index: 1000;
}
```
调一下z-index就好了
